//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyProject
    {
        public int Id { get; set; }
        public string ProjectNameTitle { get; set; }
        public string ApplySchool { get; set; }
        public string ProjectLeader { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string ProjectType { get; set; }
        public string ProjectName { get; set; }
        public string ProjectLeaderDetail { get; set; }
        public string ProjectAbstract { get; set; }
        public string ProjectMeaning { get; set; }
        public string BulidTarget { get; set; }
        public string BulidContent { get; set; }
        public string BulidTask { get; set; }
        public string ExpectEffect { get; set; }
        public string ProjectSchedule { get; set; }
        public string ProjectPay { get; set; }
        public string ProjectAttach { get; set; }
    }
}
